// pages/index.tsx
import { Dashboard } from "@/components/Dashboard";
import { Header } from "@/components/Header";
import Head from "next/head";
import { useAuth } from "@/hooks/useAuth";
import { NextPage } from 'next';

const Home: NextPage = () => {
  const { status } = useAuth();

  if (status === 'loading') {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Supera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Dashboard />
    </>
  );
};

export default Home;
